### ISSUE TITLE
Make the payerdashboard responsive 

### ISSUE THREAD

**Issue by saintmalik** [saintmalik/plixa#12]
Here is the existing page: https://plixa.xyz/payerDashboard

Send in a PR to optimize if for mobile users following the design from the figma: https://www.figma.com/file/Wu9NFHOMynq54SIZigCKpw/Plixa-web-app?type=design&node-id=269-101&mode=design

Navigate to the mobile design page on figma to see what to do

**Comment by Oluwaferanmijohn** [comment]
ok i will work on this

**Comment by Oluwaferanmijohn** [comment]
i reassigned this to the person that worked on the mobile view of this section.
